### ISSUE TITLE
Bug on launching mc with forge

### ISSUE THREAD

**Issue by bouchbi** [ZekerZhayard/ForgeWrapper#10]
HI, I have this kind of annoying issue on launching, cuz I have made a launcher for a minecraft server and it works for almost every one, except for a few people, I have this error in log : 

```
[2021-12-30 13:39:50.923] [info]  java.util.ServiceConfigurationError: io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector: Provider io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector could not be instantiated
	at java.util.ServiceLoader.fail(Unknown Source)
	at java.util.ServiceLoader.access$100(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
	at java.util.ServiceLoader$1.next(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.detector.DetectorLoader.loadDetector(DetectorLoader.java:11)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:23)
Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonElement
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	... 5 more
```

**Comment by ZekerZhayard** [comment]
how did you launch forgewrapper?

**Comment by bouchbi** [comment]
With the Minecraft-launcher-core node module

**Comment by ZekerZhayard** [comment]
I'm not familiar with your launcher, can you provide more details?
this error looks like GSON is missing in your Minecraft classpath.

**Comment by bouchbi** [comment]
I don't really know exactly how minecraft-launcher-core launches forge minecraft.
I have made a launcher with an electron application, and to handle minecraft launching I am using the minecraft-launcher-core node-module.
Then it's weird because it is not working for just a few people ?

**Comment by bouchbi** [comment]
I can open an issue on their github to get more details

**Comment by ZekerZhayard** [comment]
@Pierce01 i assume `minecraft-launcher-core` is your product, can you help me solve it?

**Comment by bouchbi** [comment]
After a bit of investigation with the persons having this issue, I found that the reason why this is not working is because they all have a cracked client (like TLauncher), and for me the issue is that TLauncher build a cracked instance of minecraft, but does not install GSON in the game files, unlike Minecraft java which does, and this would explain why ForgeWrapper is not finding the GSON lib. So nothing to do with your product, I apologize
