### ISSUE TITLE
NeoForged support

### ISSUE THREAD

**Issue by Lolothepro** [ZekerZhayard/ForgeWrapper#12]
Currently, this error occurs
```
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:115)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:147)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
Note: https://maven.neoforged.net/#/releases/net/neoforged/forge/

**Comment by ZekerZhayard** [comment]
NeoForge is still in a very early stage.
Can you provide the full java parameters used to start the game?
If you are using MultiMC, can you provide the relevant json files in the patches?

**Comment by Lolothepro** [comment]
> NeoForge is still in a very early stage. Can you provide the full java parameters used to start the game? If you are using MultiMC, can you provide the relevant json files in the patches?

[net.minecraftforge.json.txt](https://github.com/ZekerZhayard/ForgeWrapper/files/12064355/net.minecraftforge.json.txt)

**Comment by ZekerZhayard** [comment]
![image](https://github.com/ZekerZhayard/ForgeWrapper/assets/41327811/0bd5a29f-569a-4b88-bb22-df1298fd4f18)
You are installing NeoForge using the native Forge installer, which of course is wrong.
ForgeWrapper does not consider installing native Forge derivatives, so you need to manually modify this part.

**Comment by Lolothepro** [comment]
> ![image](https://user-images.githubusercontent.com/41327811/253811883-0bd5a29f-569a-4b88-bb22-df1298fd4f18.png) You are installing NeoForge using the native Forge installer, which of course is wrong. ForgeWrapper does not consider installing native Forge derivatives, so you need to manually modify this part.

For the moment, NeoForge just uses the native Forge installer. Isn't there a way to make it work without modifying the patch?

**Comment by Lolothepro** [comment]
Note: https://neoforged.net/
