### ISSUE TITLE
启动`neoforge 1.20.4`时`NoSuchMethodError`

### ISSUE THREAD

**Issue by Coloryr** [ZekerZhayard/ForgeWrapper#17]
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.JsonParser: method 'void <init>()' not found
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:140)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:126)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:159)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
```
原因是gson升级到2.10.1了

**Comment by Coloryr** [comment]
不对，是其他jar包含了gson导致的问题
