### ISSUE TITLE
PollyMC unable to install forge

### ISSUE THREAD

**Issue by Hambed1** [ZekerZhayard/ForgeWrapper#19]
PollyMC cannot install forge, gives this error:

Exception caught from launcher
java.lang.NoClassDefFoundError: cpw/mods/modlauncher/Launcher
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getLibraryDir(IFileDetector.java:55)
	at io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector.getLibraryDir(MultiMCFileDetector.java:24)
	at io.github.zekerzhayard.forgewrapper.installer.detector.MultiMCFileDetector.getInstallerJar(MultiMCFileDetector.java:34)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:141)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: cpw.mods.modlauncher.Launcher
	... 10 more
Exiting with ERROR
Process exited with code 2.

**Comment by Gemini04126** [comment]
Prism Launcher gives a similar error, but only when run in offline mode. Running normally just gives a vague `One or more subtasks failed` error.

```
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
```
Adding the `-Dforgewrapper.installer` and `-Dforgewrapper.librariesDir` arguments to the JVM gives this:
```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:59)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.installer.actions.PostProcessors.process(java.io.File, java.io.File, java.io.File, java.io.File)'
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1$ClientInstall4MultiMC.run(InstallerV1.java:35)
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1.runClientInstall(InstallerV1.java:20)
	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:26)
	... 8 more
Exiting with ERROR
```
