### ISSUE TITLE
Forge problem 

### ISSUE THREAD

**Issue by max0n4ik** [ZekerZhayard/ForgeWrapper#22]
```
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```
i use prisma launcher
	
I have been looking for a solution to this problem for two days on version 1.16.5

**Comment by ZekerZhayard** [comment]
3c6712d64a42e4ec200909912e72749499aaca79
