### ISSUE TITLE
[Bug] Unable to launch minecraft using forge

### ISSUE THREAD

**Issue by theS1LV3R** [ZekerZhayard/ForgeWrapper#3]
Every time I try to launch Minecraft through MultiMC and Forge i get the wollowing error:

<details><summary>Error log</summary>
</p>
#### Error log

```log
MultiMC version: 0.6.11-1430


Minecraft folder is:
C:/Program Files/MultiMC/instances/Default modded 1.14.4/.minecraft


Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 15.0.1, using 64-bit architecture.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Program Files/MultiMC/instances/Default modded 1.14.4/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Program Files/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Program Files/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Program Files/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Program Files/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Program Files/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Program Files/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Program Files/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Program Files/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Program Files/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Program Files/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Program Files/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Program Files/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Program Files/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Program Files/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Program Files/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Program Files/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Program Files/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Program Files/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Program Files/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Program Files/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Program Files/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Program Files/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Program Files/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.4.2/ForgeWrapper-1.4.2.jar
  C:/Program Files/MultiMC/libraries/net/minecraftforge/forge/1.14.4-28.2.0/forge-1.14.4-28.2.0-launcher.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm/6.2/asm-6.2.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.jar
  C:/Program Files/MultiMC/libraries/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.jar
  C:/Program Files/MultiMC/libraries/cpw/mods/modlauncher/4.1.0/modlauncher-4.1.0.jar
  C:/Program Files/MultiMC/libraries/cpw/mods/grossjava9hacks/1.1.0/grossjava9hacks-1.1.0.jar
  C:/Program Files/MultiMC/libraries/net/minecraftforge/accesstransformers/1.0.1-milestone.0.1+94458e7-shadowed/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar
  C:/Program Files/MultiMC/libraries/net/minecraftforge/eventbus/1.0.0-service/eventbus-1.0.0-service.jar
  C:/Program Files/MultiMC/libraries/net/minecraftforge/forgespi/1.5.0/forgespi-1.5.0.jar
  C:/Program Files/MultiMC/libraries/net/minecraftforge/coremods/1.0.0/coremods-1.0.0.jar
  C:/Program Files/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Program Files/MultiMC/libraries/com/electronwill/night-config/core/3.6.0/core-3.6.0.jar
  C:/Program Files/MultiMC/libraries/com/electronwill/night-config/toml/3.6.0/toml-3.6.0.jar
  C:/Program Files/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Program Files/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Program Files/MultiMC/libraries/net/jodah/typetools/0.6.0/typetools-0.6.0.jar
  C:/Program Files/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Program Files/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Program Files/MultiMC/libraries/com/mojang/minecraft/1.14.4/minecraft-1.14.4-client.jar

Native libraries:
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Program Files/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Program Files/MultiMC/instances/Default modded 1.14.4/.minecraft --assetsDir C:/Program Files/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 28.2.0 --fml.mcVersion 1.14.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20190829.143755

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 56132


Using onesix launcher.

2020-12-21 21:02:21,598 main WARN Advanced terminal features are not available in this environment
[32m[21:02:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, myUsername, --version, MultiMC5, --gameDir, C:/Program Files/MultiMC/instances/Default modded 1.14.4/.minecraft, --assetsDir, C:/Program Files/MultiMC/assets, --assetIndex, 1.14, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.2.0, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
[m[32m[21:02:21] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 15.0.1 by Oracle Corporation
[m[32m[21:02:22] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/NashornScriptEngineFactory
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.coremod.CoreModEngine.loadCoreMod(CoreModEngine.java:48)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.coremod.CoreModProvider.addCoreMod(CoreModProvider.java:12)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.LoadingModList.addCoreMods(LoadingModList.java:88)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:125)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:208)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.runScan(FMLServiceProvider.java:105)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:111)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:115)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1766)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:116)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:63)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[m[32m[21:02:23] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.NashornScriptEngineFactory
[m[32m[21:02:23] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[m[32m[21:02:23] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:660]: 	... 41 more
[m[32m[21:02:23] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1

Process exited with code -1.


Process exited with code -1.
```
</p>
</details>

This is a completely fresh install of both MultiMC 5, and Forge in this instance. Game launches just fine without Forge.

Minecraft version: 1.14.4
Forge version: 28.2.0
LWJGL 3 version: 3.2.2
MultiMC version: 0.6.11

**Comment by theS1LV3R** [comment]
Just did a test, no matter what version of minecraft/forge is used, it always crashes with the same error.

**Comment by ZekerZhayard** [comment]
You are using Java 15 to launch Forge for Minecraft 1.14.4, you need to use Java 8.

**Comment by theS1LV3R** [comment]
Alright, lemme try that

**Comment by ZekerZhayard** [comment]
Additionally, if you want to use Java 15 on forge 1.15.2+, you can try one of my experimental mod: https://github.com/ZekerZhayard/NashornCompatLayer (this mod **requires** java 15)

You can download it at [here](https://bintray.com/zekerzhayard/minecraft/download_file?file_path=io%2Fgithub%2Fzekerzhayard%2Fnashorn-compat-layer%2F1.0.5%2Fnashorn-compat-layer-1.0.5.jar)

**Comment by theS1LV3R** [comment]
That works, awesome. Thanks!
