### ISSUE TITLE
no main manifest attribute, in ForgeWrapper-1.5.3-LOCAL.jar

### ISSUE THREAD

**Issue by nitanmarcel** [ZekerZhayard/ForgeWrapper#8]
Doesn't run due to the following error: `no main manifest attribute, in ForgeWrapper-1.5.3-LOCAL.jar`

Command used: `java -jar "ForgeWrapper-1.5.3-LOCAL.jar" --installer="~/Downloads/forge-1.17.1-37.0.109-installer.jar" --instance="/home/nitanmarcel/.minecraft/MultiMC/instances/1.17.1/"`

**Comment by ZekerZhayard** [comment]
>Run ./gradlew converter:build command in terminal and get the jar from ./converter/build/libs

**Comment by nitanmarcel** [comment]
> 

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonElement
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3475)
        at java.base/java.lang.Class.getMethod0(Class.java:3461)
        at java.base/java.lang.Class.getMethod(Class.java:2193)
        at io.github.zekerzhayard.forgewrapper.converter.Main.main(Main.java:29)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:852)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 6 more
        ```

**Comment by ZekerZhayard** [comment]
```
java -jar "ForgeWrapper-1.5.3-LOCAL.jar" "--installer=~/Downloads/forge-1.17.1-37.0.109-installer.jar" "--instance=/home/nitanmarcel/.minecraft/MultiMC/instances/1.17.1/"
```

notice the double quotes location
